// src/components/react/Blog.tsx
import { useState, useEffect } from 'react';
import type { CollectionEntry } from 'astro:content';
import ArrowCard from '@components/react/ArrowCard';
import { cn } from '@lib/utils';

type Props = {
	tags: string[];
	data: CollectionEntry<'blog'>[];
};

const Blog: React.FC<Props> = ({ data, tags }) => {
	const [filter, setFilter] = useState<Set<string>>(new Set());
	const [posts, setPosts] = useState<CollectionEntry<'blog'>[]>([]);

	useEffect(() => {
		setPosts(
			data.filter((entry) =>
				Array.from(filter).every((value) =>
					entry.data.tags.some((tag: string) => tag.toLowerCase() === value.toLowerCase()),
				),
			),
		);
	}, [data, filter]);

	const toggleTag = (tag: string) => {
		setFilter((prev) => {
			const newSet = new Set(prev);
			if (newSet.has(tag)) {
				newSet.delete(tag);
			} else {
				newSet.add(tag);
			}
			return newSet;
		});
	};

	return (
		<div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
			<div className="col-span-3 sm:col-span-1">
				<div className="sticky top-24">
					<div className="text-sm font-semibold uppercase mb-2 text-black dark:text-white">Filter</div>
					<ul className="flex flex-wrap sm:flex-col gap-1.5">
						{tags.map((tag) => (
							<li key={tag}>
								<button
									onClick={() => toggleTag(tag)}
									className={cn(
										'w-full px-2 py-1 rounded',
										'whitespace-nowrap overflow-hidden overflow-ellipsis',
										'flex gap-2 items-center',
										'bg-black/5 dark:bg-white/10',
										'hover:bg-black/10 hover:dark:bg-white/15',
										'transition-colors duration-300 ease-in-out',
										filter.has(tag) && 'text-black dark:text-white',
									)}
								>
									<svg
										className={cn(
											'size-5 fill-black/50 dark:fill-white/50',
											'transition-colors duration-300 ease-in-out',
											filter.has(tag) && 'fill-black dark:fill-white',
										)}
									>
										<use href={'/ui.svg#square'} className={cn(!filter.has(tag) ? 'block' : 'hidden')} />
										<use href={'/ui.svg#square-check'} className={cn(filter.has(tag) ? 'block' : 'hidden')} />
									</svg>
									{tag}
								</button>
							</li>
						))}
					</ul>
				</div>
			</div>
			<div className="col-span-3 sm:col-span-2">
				<div className="flex flex-col">
					<div className="text-sm uppercase mb-2">
						SHOWING {posts.length} OF {data.length} POSTS
					</div>
					<ul className="flex flex-col gap-3">
						{posts.map((post) => (
							<li key={post.slug}>
								<ArrowCard entry={post} />
							</li>
						))}
					</ul>
				</div>
			</div>
		</div>
	);
};

export default Blog;

// src/components/solid/Blog.tsx
import type { CollectionEntry } from 'astro:content';
import { createEffect, createSignal, For } from 'solid-js';
import ArrowCard from '@components/solid/ArrowCard';
import { cn } from '@lib/utils';

type Props = {
	tags: string[];
	data: CollectionEntry<'blog'>[];
};

export default function Blog({ data, tags }: Props) {
	const [filter, setFilter] = createSignal(new Set<string>());
	const [posts, setPosts] = createSignal<CollectionEntry<'blog'>[]>([]);

	createEffect(() => {
		setPosts(
			data.filter((entry) =>
				Array.from(filter()).every((value) =>
					entry.data.tags.some((tag: string) => tag.toLowerCase() === String(value).toLowerCase()),
				),
			),
		);
	});

	function toggleTag(tag: string) {
		setFilter((prev) => new Set(prev.has(tag) ? [...prev].filter((t) => t !== tag) : [...prev, tag]));
	}

	return (
		<div class="grid grid-cols-1 sm:grid-cols-3 gap-6">
			<div class="col-span-3 sm:col-span-1">
				<div class="sticky top-24">
					<div class="text-sm font-semibold uppercase mb-2 text-black dark:text-white">Filter</div>
					<ul class="flex flex-wrap sm:flex-col gap-1.5">
						<For each={tags}>
							{(tag) => (
								<li>
									<button
										onClick={() => toggleTag(tag)}
										class={cn(
											'w-full px-2 py-1 rounded',
											'whitespace-nowrap overflow-hidden overflow-ellipsis',
											'flex gap-2 items-center',
											'bg-black/5 dark:bg-white/10',
											'hover:bg-black/10 hover:dark:bg-white/15',
											'transition-colors duration-300 ease-in-out',
											filter().has(tag) && 'text-black dark:text-white',
										)}
									>
										<svg
											class={cn(
												'size-5 fill-black/50 dark:fill-white/50',
												'transition-colors duration-300 ease-in-out',
												filter().has(tag) && 'fill-black dark:fill-white',
											)}
										>
											<use href={`/ui.svg#square`} class={cn(!filter().has(tag) ? 'block' : 'hidden')} />
											<use href={`/ui.svg#square-check`} class={cn(filter().has(tag) ? 'block' : 'hidden')} />
										</svg>
										{tag}
									</button>
								</li>
							)}
						</For>
					</ul>
				</div>
			</div>
			<div class="col-span-3 sm:col-span-2">
				<div class="flex flex-col">
					<div class="text-sm uppercase mb-2">
						SHOWING {posts().length} OF {data.length} POSTS
					</div>
					<ul class="flex flex-col gap-3">
						{posts().map((post) => (
							<li>
								<ArrowCard entry={post} />
							</li>
						))}
					</ul>
				</div>
			</div>
		</div>
	);
}
