// src/components/Search.tsx
import type { CollectionEntry } from 'astro:content';
import { createEffect, createSignal } from 'solid-js';
import Fuse from 'fuse.js';
import ArrowCard from '@components/ArrowCard';

type Props = {
	data: CollectionEntry<'blog'>[];
};

export default function Search({ data }: Props) {
	const [query, setQuery] = createSignal('');
	const [results, setResults] = createSignal<CollectionEntry<'blog'>[]>([]);

	const fuse = new Fuse(data, {
		keys: ['slug', 'data.title', 'data.summary', 'data.tags'],
		includeMatches: true,
		minMatchCharLength: 2,
		threshold: 0.4,
	});

	createEffect(() => {
		if (query().length < 2) {
			setResults([]);
		} else {
			setResults(fuse.search(query()).map((result) => result.item));
		}
	});

	const onInput = (e: Event) => {
		const target = e.target as HTMLInputElement;
		setQuery(target.value);
	};

	return (
		<div class="flex flex-col">
			<div class="relative">
				<input
					name="search"
					type="text"
					value={query()}
					onInput={onInput}
					autocomplete="off"
					spellcheck={false}
					placeholder="What are you looking for?"
					class="w-full px-2.5 py-1.5 pl-10 rounded outline-none text-black dark:text-white bg-black/5 dark:bg-white/15 border border-black/10 dark:border-white/20 focus:border-black focus:dark:border-white"
				/>
				<svg class="absolute size-6 left-1.5 top-1/2 -translate-y-1/2 stroke-current">
					<use href={`/ui.svg#search`} />
				</svg>
			</div>
			{query().length >= 2 && results().length >= 1 && (
				<div class="mt-12">
					<div class="text-sm uppercase mb-2">
						Found {results().length} results for {`'${query()}'`}
					</div>
					<ul class="flex flex-col gap-3">
						{results().map((result) => (
							<li>
								<ArrowCard entry={result} pill={true} />
							</li>
						))}
					</ul>
				</div>
			)}
		</div>
	);
}

// src/components/react/Search.tsx
import type { CollectionEntry } from 'astro:content';
import ArrowCard from '@components/react/ArrowCard';
import Fuse from 'fuse.js';
import { useEffect, useState } from 'react';

type Props = {
	data: CollectionEntry<'blog'>[];
};

const Search: React.FC<Props> = ({ data }) => {
	const [query, setQuery] = useState('');
	const [results, setResults] = useState<CollectionEntry<'blog'>[]>([]);

	const fuse = new Fuse(data, {
		keys: ['slug', 'data.title', 'data.summary', 'data.tags'],
		includeMatches: true,
		minMatchCharLength: 2,
		threshold: 0.4,
	});

	useEffect(() => {
		if (query.length < 2) {
			setResults([]);
		} else {
			const fuseResults = fuse.search(query).map((result) => result.item);
			setResults(fuseResults);
		}
	}, [query, data]);

	const onInput = (e: React.ChangeEvent<HTMLInputElement>) => {
		setQuery(e.target.value);
	};

	return (
		<div className="flex flex-col">
			<div className="relative">
				<input
					autoComplete="off"
					className="w-full rounded border border-black/10 bg-black/5 px-2.5 py-1.5 pl-10 text-black outline-none focus:border-black dark:border-white/20 dark:bg-white/15 dark:text-white focus:dark:border-white"
					name="search"
					onChange={onInput}
					placeholder="What are you looking for?"
					spellCheck={false}
					type="text"
					value={query}
				/>
				<svg className="-translate-y-1/2 absolute top-1/2 left-1.5 size-6 stroke-current">
					<use href={'/ui.svg#search'} />
				</svg>
			</div>
			{query.length >= 2 && results.length >= 1 && (
				<div className="mt-12">
					<div className="mb-2 text-sm uppercase">
						Found {results.length} results for {`'${query}'`}
					</div>
					<ul className="flex flex-col gap-3">
						{results.map((result) => (
							<li key={result.slug}>
								<ArrowCard entry={result} pill={true} />
							</li>
						))}
					</ul>
				</div>
			)}
		</div>
	);
};

export default Search;
